name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main','rewiev-3']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Set lower case owner name
        run: |
          echo "REPO=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Echo repo name
        run: |
          echo "repo-${REPO}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ env.REPO }}/sp18_backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ env.REPO }}/sp18_frontend:latest

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: ghcr.io/${{ env.REPO }}/sp18_server:latest